# Generated by Django 4.0.4 on 2022-08-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_produkty_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sklep',
                'verbose_name_plural': 'Sklepy',
            },
        ),
        migrations.CreateModel(
            name='Oferty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.produkty')),
                ('sklep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.sklepy')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofrety',
            },
        ),
        migrations.AddField(
            model_name='produkty',
            name='sklepy',
            field=models.ManyToManyField(through='Produkty.Oferty', to='Produkty.sklepy'),
        ),
    ]
