# Generated by Django 4.0.4 on 2022-08-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0006_sklepy_oferty_produkty_sklepy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferty',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
    ]
