# Generated by Django 4.0.4 on 2022-08-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0010_remove_konto_data_dolaczenia_remove_konto_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiadomienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treść', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('konto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.konto')),
                ('oferta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.oferty')),
            ],
        ),
    ]
