# Generated by Django 4.0.4 on 2022-08-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0011_powiadomienia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powiadomienia',
            options={'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
    ]
