# Generated by Django 4.0.4 on 2022-08-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0012_alter_powiadomienia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienia',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
