# Generated by Django 4.0.4 on 2022-08-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0013_powiadomienia_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='cena',
        ),
    ]
