# Generated by Django 4.0.4 on 2022-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0015_promocje'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferty',
            name='promocyjna_cena',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
