# Generated by Django 4.0.4 on 2022-08-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0016_oferty_promocyjna_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienia',
            name='konto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.konto'),
        ),
        migrations.AlterField(
            model_name='powiadomienia',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.oferty'),
        ),
    ]
