# Generated by Django 4.0.4 on 2022-08-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0018_powiadomienia_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powiadomienia',
            name='viewed',
        ),
    ]
