# Generated by Django 4.0.4 on 2022-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0019_remove_powiadomienia_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='promocyjna_cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
