# Generated by Django 4.0.4 on 2022-08-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0020_alter_oferty_promocyjna_cena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiadomienia_produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treść', models.TextField()),
                ('status', models.BooleanField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('konto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.konto')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.produkty')),
            ],
            options={
                'verbose_name': 'Powiadomienie_P',
                'verbose_name_plural': 'Powiadomienia_P',
            },
        ),
    ]
