# Generated by Django 4.0.4 on 2022-09-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0022_remove_powiadomienia_produkt_produkt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powiadomienia_produkt',
            options={'verbose_name': 'Powiadomienie_Produkt', 'verbose_name_plural': 'Powiadomienia_Produkt'},
        ),
        migrations.AddField(
            model_name='produkty',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
