# Generated by Django 4.0.4 on 2022-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0023_alter_powiadomienia_produkt_options_produkty_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienia_produkt',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
